=== enriquee17/Ejercicios/src/LenguajedeMarcas/correo.dtd
<!ELEMENT emails (email*)>
<!ELEMENT email (para*, cc*, cco*, asunto, cuerpo, adjunto*)>

<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
<!ELEMENT adjunto (#PCDATA)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT nimetype (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>

=== enriquee17/Ejercicios/src/LenguajedeMarcas/ejerciciocorreo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE placasbaseejercicio SYSTEM "correo.dtd"> 
<emails>
	<email>
		<para></para>
		<cc></cc>
		<cco></cco>
		<asunto></asunto>
		<cuerpo></cuerpo>
		<adjunto>
			<nombre></nombre>
			<nimetype></nimetype>
			<longitud></longitud>
		</adjunto>	
	</email>
</emails>
